### PR TITLE
use Composer for package management and PHPCS for code style

### PR DESCRIPTION
**Pull request by markparolisi**
This adds support for Composer and PHPCS in an easy build process. Will be used for linting, tests, and packaging for deploys. This just sets up the config

### CODE REVIEW

**Comment by lautarodragan** [comment]
@markparolisi I'm trying to test this using `composer wp-package` but I'm getting the following error when uploading `build.zip` to my WP instance:

```
The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
```

I tried running `zip build.zip assets includes languages LICENSE poet.php readme.txt` instead of tar and that worked a step further, but then failed to activate with:

```
Warning: require(/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/build-2/includes/class-poet.php): failed to open stream: No such file or directory in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/build-2/poet.php on line 46

Fatal error: require(): Failed opening required '/opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/build-2/includes/class-poet.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/build-2/poet.php on line 46
```

**Comment by markparolisi** [comment]
Thanks, @lautarodragan I'll check on that task. I wrote it a while back and I'm sure the plugin has changed and I never actually checked my work there :/
Did you try running the lint command as well?

**Comment by lautarodragan** [comment]
No worries. Tried a bit and looks like this works:

```
zip -r poet.zip admin assets includes languages LICENSE poet.php public readme.txt
```

Seems like the file needs to be a `zip`, and a couple of directories were missing from the package.

With that I was able to upload and install the plugin: http://54.87.184.5/2018/07/04/is-there-a-bug-in-the-new-version/

I was also able to create a new post and get it anchored: http://54.87.184.5/2018/11/21/plain-truth-is-nothing/

So far so good.

Created a PR to your PR with this fix: https://github.com/poetapp/wordpress-plugin/pull/41/files

**Comment by markparolisi** [comment]
Yeah I'll merge your fixes and get this 100% straightened out. Adding a Travis config and docker-compose will be easy enough as well.
Once I get all of the four outstanding PRs all merged (into a v1.0.3 branch) we can run some final tests before packaging for a SVN release.

**Pull request merged**
