### PR TITLE
WP Standards and such

### PR DESCRIPTION
**Pull request by markparolisi**
I've made a few updates to the structure. No functional changes.

* Used Composer instead of Phing
* Using PHPCS to get the code (more) to WP standards
* Using namespaces, square bracket arrays, and some other more "modern" PHP syntax.
* Minor style update to the admin settings page
* Scaffolded some PHPUnit testing

Everything _should_ work out-of-the-box for you. Will just have to `composer install` to run any of the dev tasks. 

I have some more things I'd think will help, but this is a start.

### CODE REVIEW

**Comment by lautarodragan** [comment]
Thanks for your PR @markparolisi ! It really is a lot of work. 

I know @haydenyoung had been working on similar things — he had an open PR on coding standards and directory structures and such. Ideally I'd love for you guys to sync, I see both of you made some valuable improvements.

I also noticed you upped the minimum required WP version to 7. I'm not really sure whether WP 5 is used anymore, but would rather keep it as compatible as possible for now. Are there some significant features we're missing by staying compatible with an older version?

**Comment by markparolisi** [comment]
I saw @haydenyoung's PR after I pushed mine (because isn't that always how it goes). Agreed we have a lot of overlap. I think the best thing going for my PR is the updated tooling around Composer, PHPCS, PHPUnit, etc. 

As for PHP 7, it's been out in full for a few years now. I don't think I'm actually using any PHP7 specific syntax (e.g. type hinting), but that's what all of my machines run so I set it to that. There are, of course, tons of advantages for running PHP7. Most notably the speed and memory efficiency. 

Having this be PHP 5 compatible should be fine. You still get most things like namespaces and such. It just leads back to a question I had in #27 about the audience. If this is for bloggers on their GoDaddy domains, then you'd need to support 5, if it's for enterprise-level publishers, then 7 is the norm.

**Comment by ericelliott** [comment]
I don't know what version we need to support, but I'm fairly sure support for users on their own domains is important.

**Comment by markparolisi** [comment]
Supporting one's own domain isn't the issue. It's just the old versions of a language that won't have support by the end of this year.
http://php.net/supported-versions.php
But, unfortunately, I'm sure you will find that most web servers are running < 7 right now, especially in small site, shared host settings.

**Comment by ericelliott** [comment]
Understood. Any way to get PHP version data across blogs in the wild to decide what we need to support?

**Comment by geoffturk** [comment]
@markparolisi Is there anything you strongly think we should carry over from this PR and/or merge on top of (see conflicts)?

**Comment by markparolisi** [comment]
I'd say moving from Phing to Composer, using PHPCS, and using PHPUnit

**Comment by markparolisi** [comment]
closing this ticket as it is too broad. A more focused PR is here: #40 
Will have another for PHPUnit and potentially a third for other random code style updates.

**Pull request closed without merging**
